
server:
  port: 80

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: business-api
          uri: http://192.168.200.79:8090/user/
          predicates:
            - Path=/user/**
          filters:
            - Auth
