server:
  port: 8092


spring:
  application:
    name: finance-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      #        server-addr: ${nacos.addr}:${nacos.port}
      config:
        server-addr: 127.0.0.1:8848
    stream:
      kafka:
        binder:
          brokers: 192.168.2.18:9092
          auto-create-topics: true
      bindings:
        output:
          destination: test-topic
        output_1:
          destination: test-topic-1
        output_2:
          destination: test-topic-2
        input:
          destination: test-topic
          group: test-group
        input_1:
          destination: test-topic-1
          group: test-group
        input_2:
          destination: test-topic-2
          group: test-group

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


