server:
  port: 8091

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      #        server-addr: ${nacos.addr}:${nacos.port}
      config:
        server-addr: 127.0.0.1:8848
#  zipkin:
#    sender:
#      type: web
#    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0
    web:
      enabled: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


