server:
  port: 8090

spring:
  application:
    name: business-web
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel 使用nacos作为配置源
    sentinel:
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            ruleType: 0


logging:
  config: classpath:log4j2.xml
